accounts/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from accounts.views import account_views, profile_views, kakaopay_views  

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', account_views.signup, name='signup'),	
    path('profile/<int:pk>', profile_views.profile, name='profile'),
    path('profile/<int:pk>/register', profile_views.profile_register, name='profile_register'),
    path('profile/<int:pk>/modify', profile_views.profile_modify, name='profile_modify'),
    path('profile/<int:pk>/point', profile_views.point_charge, name='point_charge'),
    path('kakaoPay/', kakaopay_views.kakaoPay, name='kakaoPay'),
    path('paySuccess/', kakaopay_views.paySuccess, name='paySuccess'),
    path('payFail/', kakaopay_views.payFail, name='payFail'),
    path('payCancel/', kakaopay_views.payCancel, name='payCancel'),
]

if settings.DEBUG: 
    urlpatterns += static(
        settings.MEDIA_URL, 
        document_root = settings.MEDIA_ROOT
    )

data4u/urls.py
from django.urls import path, include
from .views import base_views, question_views, answer_views

app_name = 'data4u'

urlpatterns = [
    # base views
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),
    
    # question views
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),
    
    # answer views
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),
]

data4u_mvp/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from data4u.views import base_views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('data4u/', include('data4u.urls')),
    path('accounts/', include('accounts.urls')),
    path('', base_views.index, name='index'),
]

# MEDIA_URL로 들어오는 요청에 대해 MEDIA_ROOT 경로를 탐색한다.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    point = models.IntegerField(default=0)
    nickname = models.TextField(max_length=10)
    description = models.TextField(blank=True, default="안녕하세요.")
    image = models.ImageField(blank=True, upload_to="accounts/profile_img")
    
    def __str__(self):
        return self.nickname
    

data4u/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Question_4(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    subject = models.CharField(max_length=200)
    content1 = models.TextField()
    content2 = models.TextField()
    content3 = models.TextField()
    content4 = models.TextField()
    create_date = models.DateTimeField()
    user_point = models.IntegerField(default=0)
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_question')
    
    def __str__(self):
        return self.subject
    

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question_4, on_delete=models.CASCADE)
    content = models.IntegerField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')
    

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

        
        
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["image", "nickname", "description"]

accounts/views/account_views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, get_user_model
from accounts.forms import UserForm
import os
import requests
import time
from django.conf import settings
from django.shortcuts import redirect
from django.middleware.csrf import get_token
from rest_framework import status
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from rest_framework.views import APIView
from drf_yasg.utils import swagger_auto_schema

from ..serializers import *
# Create your views here.

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)	#사용자 인증
            login(request, user)
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'accounts/signup.html', {'form':form})


# kakao 로그인
KAKAO_CONFIG = {
    "KAKAO_REST_API_KEY": '0a32dcc9e9e21081bf2ca1260b837ae8',
    "KAKAO_REDIRECT_URI": "https://practice-poll.run.goorm.io/accounts/login/kakao/callback/",
    "KAKAO_CLIENT_SECRET_KEY": 'eBdC1RIvBxKDb0haUWHQNNRIHmFmjYmr', 
}

kakao_login_uri = "https://kauth.kakao.com/oauth/authorize"
kakao_token_uri = "https://kauth.kakao.com/oauth/token"
kakao_profile_uri = "https://kapi.kakao.com/v2/user/me"

accounts/views/kakaopay_views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, get_user_model
from accounts.forms import UserForm
from django.contrib import messages
import requests
from accounts.models import Profile
# Create your views here.


def kakaoPay(request):
    if request.method == 'POST' :
        _admin_key = 'e7b6071057ccc32ec53f3df582246d77' # 입력필요
        _url = f'https://kapi.kakao.com/v1/payment/ready'
        _headers = {
            'Authorization': f'KakaoAK {_admin_key}',
            'Content-type': 'application/x-www-form-urlencoded;charset=utf-8',
        }
        _data = {
            'cid': 'TC0ONETIME',
            'partner_order_id': 1001 , #주문번호
    	    'partner_user_id': request.user.id,   # 유저 아이디
    	    'item_name':'포인트',                   # 구매 물품 이름
    	    'quantity':1,                        # 구매 물품 가격
    	    'total_amount':request.POST['point'],                 # 구매 물품 가격
    	    'vat_amount':0,                    # 구매 물품 비과세
    	    'tax_free_amount':0,
    	    # 내 애플리케이션 -> 앱설정 / 플랫폼 - WEB 사이트 도메인에 등록된 정보만 가능합니다
    	    # * 등록 : http://IP:8000 
    	    'approval_url':'https://data4u-mvp.herokuapp.com/accounts/paySuccess', 
            'fail_url':'https://data4u-mvp.herokuapp.com/accounts/payFail',
            'cancel_url':'https://data4u-mvp.herokuapp.com/accounts/payCancel'
        }
        res = requests.post(_url, data=_data, headers=_headers)
        _result = res.json()
        request.session['tid'] = _result['tid']
        next_url = _result['next_redirect_pc_url']  
        return redirect(next_url)
    
    try:
        profile = get_object_or_404(Profile, user=request.user)
    except:
        messages.error(request, '프로필을 먼저 등록해주세요.')
        return redirect('accounts:profile', request.user.id)
    return render(request, 'accounts/kakaoPay.html')


def paySuccess(request):
    _url = 'https://kapi.kakao.com/v1/payment/approve'
    _admin_key = 'e7b6071057ccc32ec53f3df582246d77' # 입력필요
    _headers = {
        'Authorization': f'KakaoAK {_admin_key}'
    }
    _data = {
        'cid':'TC0ONETIME',
        'tid': request.session['tid'],
        'partner_order_id':1001,
        'partner_user_id':request.user.id,
        'pg_token': request.GET['pg_token']
    }
    _res = requests.post(_url, data=_data, headers=_headers)
    #amount = _res.json()['amount']['total']
    _result = _res.json()
    context = {
        'res' : _result,
    }
    if _result.get('msg'):
        messages.success(request, f'포인트 충전을 실패했습니다.')
        context = {
        'partner_order_id': _result['partner_order_id'],
        'item_name': _result['item_name'],
        'approved_at': _result['approved_at'],
        'total': _result['amount']['total'],
    	}
        return render(request, 'accounts/payFail.html', context)
    else:
        # point 충전
        profile = get_object_or_404(Profile, user=request.user)
        profile.point += _result['amount']['total']
        profile.save()
        messages.success(request, f'{_result["amount"]["total"]} 포인트가 충전되었습니다.')
        return render(request, 'accounts/paySuccess.html', context)

        
def payFail(request):
    return render(request, 'accounts/payFail.html')

def payCancel(request):
    return render(request, 'accounts/payCancel.html')

accounts/views/profile_views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator
from accounts.models import Profile
from accounts.forms import UserForm, ProfileForm
from data4u.models import Question_4, Answer
# Create your views here.

@login_required(login_url='accounts:login')
def profile(request, pk):
    user = get_object_or_404(User, pk=pk)
    question_list = Question_4.objects.filter(author=pk)
    question_count = question_list.count()
    page = request.GET.get('page', '1')
    paginator = Paginator(question_list, 5)
    page_obj = paginator.get_page(page)
    context = {'question_list':page_obj, 'question_count':question_count}
    return render(request, 'accounts/profile.html', context)

@login_required(login_url='accounts:login')
def profile_register(request, pk):
    if request.method == 'POST' :
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            messages.success(request, '프로필이 등록되었습니다.')
            # profile 페이지 이동
            return redirect('accounts:profile', pk)
    else:
        form = ProfileForm()
    context = {'form' : form}
    return render(request, 'accounts/profile_form.html', context)


@login_required(login_url='accounts:login')
def profile_modify(request, pk):
    profile = get_object_or_404(Profile, user=request.user)
    if request.method == 'POST' :
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            messages.success(request, '프로필 정보가 수정되었습니다.')
            # profile 페이지 이동
            return redirect('accounts:profile', pk)
    else:
        form = ProfileForm(instance=profile)
    context = {'form' : form}
    return render(request, 'accounts/profile_form.html', context)

@login_required(login_url='accounts:login')
def point_charge(request, pk):
    return render(request, 'accounts/point_charge.html')

templates/accounts/kakaoPay.html
{% extends 'base.html' %}
{% load static %}
{% load data4u_filter %}
{% block content %}

<!-- message 표시 -->
{% if messages %}
<div class="alert alert-danger my-3" role="alert">
{% for message in messages %}
    <strong>{{ message.tags }}</strong>
    <ul><li>{{ message.message }}</li></ul>
{% endfor %}
</div>
{% endif %}
<div class="card justify-content-center py-5">
  <!-- <h2 class="text-center my-4 col-12">결제방</h2> -->
  <div class="card-body">
    <h3 class="text-center my-3">포인트 구매하기</h3>
      <form method="post">
          {% csrf_token %}
          <div class="justify-content-center text-center my-3 row">
              <div class="w-50 mt-5">
                  <label for='point' style="font-weight:bold;">POINT</label>
                  <div class="input-group mt-3">
                      <input type="number" class="form-control" id='point' name='point'>
                      <div class="input-group-append">
                          <span class="input-group-text">KW</span>
                      </div>
                  </div>
              </div>
          </div>
          <div class = "justify-content-center text-center my-3 row">
              <input type="image" src='{% static "img/kakaopay.png" %}' style="width:110px;" alt='카카오페이'>
          </div>
      </form>
    <div class="mt-5 pt-3 text-center">
      <a href="{% url 'accounts:profile' user.id %}" class="btn mt-5" style="font-weight:bold; background-color: #FFD200;">메인으로 돌아가기</a>
    </div>
  </div>
</div>
{% endblock %}

templates/accounts/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'accounts:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

templates/accounts/payCancel.html
{% extends 'base.html' %}
{% load data4u_filter %}
{% block content %}
<!-- message 표시 -->
{% if messages %}
<div class="alert alert-danger my-3" role="alert">
{% for message in messages %}
    <strong>{{ message.tags }}</strong>
    <ul><li>{{ message.message }}</li></ul>
{% endfor %}
</div>
{% endif %}
<div class="card justify-content-center py-5">
  <h2 class="text-center my-5 col-12">결제를 취소합니다!</h2>
  <div>
    <div class="mt-5 pt-3 text-center">
      <a href="{% url 'accounts:profile' user.id %}" class="btn" style="font-weight:bold; background-color: #FFD200;">메인으로 돌아가기</a>
    </div>
  </div>
</div>
{% endblock %}

templates/accounts/profile.html
{% extends 'base.html' %}
{% load data4u_filter %}
{% block content %}
<!-- message 표시 -->
{% if messages %}
<div class="alert alert-danger my-3" role="alert">
{% for message in messages %}
    <strong>{{ message.tags }}</strong>
    <ul><li>{{ message.message }}</li></ul>
{% endfor %}
</div>
{% endif %}
<section class="h-100 gradient-custom-2">
  <div class="container py-4 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-7">
        <div class="card">
          {% if user.profile %}
          <div class="rounded-top text-white d-flex flex-row" style="background-color: #0078FF; height:200px;">
            <div class="ms-4 mt-5 d-flex flex-column" style="width: 150px; z-index: 1;">
              <img src="{{ user.profile.image.url }}"
                alt="Generic placeholder image" class="img-fluid img-thumbnail mt-4 mb-2"
                style="width: 88%; height:88%; object-fit: cover;">
            </div>
            <div class="ms-3" style="margin-top: 130px;">
              <h5>{{ user.username }}</h5>
              <p style="font-size:70%;">{{ user.email }}</p>
            </div>
          </div>
          <div class="p-4 text-black" style="background-color: #f8f9fa;">
            <div class="d-flex justify-content-start text-center py-1">
              <div>
              	  <a href="{% url 'accounts:profile_modify' user.id %}">
              	      <button type="button" class="btn btn-sm" style="color: white; background-color: #0099FF;" data-mdb-ripple-color="dark">Edit profile</button>
              	  </a>
              </div>
            </div>
            <div class="d-flex justify-content-end text-center py-1">
              <div>
                <p class="mb-1 h5">{{ user.profile.point }}</p>
                <p class="small text-muted mb-0">Point</p>
              </div>
            </div>
          </div>
          {% else %}
    	  <div class="card">
    	      <div class="card-body">
    	          <div class="d-flex justify-content-start">
    	              <div class="badge text-dark p-2 text-start">
    	                  <a href="{% url 'accounts:profile_register' user.id %}">프로필을 등록하세요.</a>
    	              </div>
    	          </div>
    	      </div>
    	  </div>
          {% endif %}
          <div class="card-body p-4 text-black">
            <div class="row my-3">
                <div class="col-7 mt-2"><a href="{% url 'data4u:question_create' %}" class="btn btn-sm" style="color: white; background-color: #0099FF;">질문하러 가기</a></div>
                <div><p class="mb-1 h5 mt-1"><a href="{% url 'accounts:kakaoPay' %}" class="btn btn-sm" style="color: white; background-color: #0099FF;">포인트 충전</a></p></div>
            </div>
            <!-- <div class="mb-5 mt-13">
              <p class="lead fw-normal mb-1">About</p>
              <div class="p-4">
                <p class="font-italic mb-1">{{ user.profile.description }}</p>
              </div>
            </div> -->
            <div class="d-flex justify-content-between align-items-center mb-4 mt-5">
              <p class="lead fw-normal mb-0">Recent Questions</p>
            </div>
            <h4 class="mt-3">현재 {{ question_count }}개의 질문을 했습니다.</h4>
            <table class="table mt-4">
                <thead>
                <tr class="text-center table-dark">
                    <th>번호</th>
                    <th>제목</th>
                    <th>질문자</th>
                    <th>작성 일시</th>
                </tr>
                </thead>
                <tbody>
                {% if question_list %}
                {% for question in question_list %}
                <tr class="text-center">
                    <td>
                        <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                        {{ question_list.paginator.count | sub:question_list.start_index | sub:forloop.counter0|add:1 }}
                    </td>
                    <td class="text-start">
                        <a href="{% url 'data4u:detail' question.id %}" style='text-decoration:none; font-weight:bold;'>{{ question.subject }}</a>
                    	{% if question.answer_set.count > 0 %}
                        <span class="text-danger small mx-2">{{ question.answer_set.count }}</span>
                        {% endif %}
                    </td>
                    <td>{{ question.author.username }}</td>
                    <td>{{ question.create_date }}</td>
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                    <td colspan="4">질문이 없습니다.</td>
                </tr>
                {% endif %}
                </tbody>
            </table>
            <!-- 페이징처리 시작 -->
            <ul class="pagination justify-content-center">
                <!-- 이전페이지 -->
                {% if question_list.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
                </li>
                {% endif %}
                <!-- 페이지리스트 -->
                {% for page_number in question_list.paginator.page_range %}
                {% if page_number >= question_list.number|add:-2 and page_number <= question_list.number|add:2 %}
                {% if page_number == question_list.number %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
                {% endif %}
            	{% endif %}
                {% endfor %}
                <!-- 다음페이지 -->
                {% if question_list.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
                </li>
                {% endif %}
            </ul>
            <!-- 페이징처리 끝 -->
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


{% endblock %}

templates/accounts/profile_test1.html
{% extends 'base.html' %}
{% load data4u_filter %}
{% block content %}
<div class="container my-3">
    <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ user.username }}님</h2>
    {% if user.profile %}
    <div style="hegiht:50%;">
        <img src="{{ user.profile.image.url }}" style="width=30%; hegiht:30%; object-fit:cover;" alt="Card image cap">
        <div>
            <div class="d-flex justify-content-start">
                <div class="badge text-dark p-2 text-start" style="font-size: 110%;">
                    현재 포인트 {{ user.profile.point }} P
                </div>
                <div class="badge text-dark p-2 text-start">
                    <a href="{% url 'accounts:kakaoPay' %}" class="btn btn-sm" style="color: white; background-color: #0099FF;">포인트 충전</a>
                </div>
            </div>
        </div>
    </div>
    {% else %}
    <div class="card">
        <div class="card-body">
            <div class="d-flex justify-content-start">
                <div class="badge text-dark p-2 text-start">
                    <a href="{% url 'accounts:profile_register' user.id %}">프로필을 등록하세요.</a>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
    <div class="row my-3">
        {% if user.profile %}
        <div class="col-6 mt-2"><a href="{% url 'accounts:profile_modify' user.id %}" class="btn btn-sm" style="color: white; background-color: #0099FF;">프로필 수정</a></div>
        {% endif %}
        <div class="col-7 mt-2"><a href="{% url 'data4u:question_create' %}" class="btn btn-sm" style="color: white; background-color: #0099FF;">질문하러 가기</a></div>
    </div>
    <!-- <div class="card">
        <div class="card-body">
            <div class="d-flex justify-content-start">
                <div class="badge text-dark p-2 text-start">
                    현재 포인트는 ___ 입니다.
                </div>
            </div>
        </div>
    </div> -->
    <h4 class="mt-5">현재 {{ question_count }}개의 질문을 했습니다.</h4>
    <table class="table mt-4">
        <thead>
        <tr class="text-center table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>질문자</th>
            <th>작성 일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr class="text-center">
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ question_list.paginator.count | sub:question_list.start_index | sub:forloop.counter0|add:1 }}
            </td>
            <td class="text-start">
                <a href="{% url 'data4u:detail' question.id %}" style='text-decoration:none; font-weight:bold;'>{{ question.subject }}</a>
            	{% if question.answer_set.count > 0 %}
                <span class="text-danger small mx-2">{{ question.answer_set.count }}</span>
                {% endif %}
            </td>
            <td>{{ question.author.username }}</td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-2 and page_number <= question_list.number|add:2 %}
        {% if page_number == question_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% endif %}
    	{% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
</div>
{% endblock %}

templates/accounts/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'accounts:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}