data4u/urls.py
from django.urls import path, include
from .views import base_views, question_views, answer_views

app_name = 'data4u'

urlpatterns = [
    # base views
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),
    
    # question views
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),
    
    # answer views
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),
]

data4u_mvp/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from data4u.views import base_views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('data4u/', include('data4u.urls')),
    path('accounts/', include('accounts.urls')),
    path('', base_views.index, name='index'),
]

# MEDIA_URL로 들어오는 요청에 대해 MEDIA_ROOT 경로를 탐색한다.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

data4u/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Question_4(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    subject = models.CharField(max_length=200)
    content1 = models.TextField()
    content2 = models.TextField()
    content3 = models.TextField()
    content4 = models.TextField()
    create_date = models.DateTimeField()
    user_point = models.IntegerField(default=0)
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_question')
    
    def __str__(self):
        return self.subject
    

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question_4, on_delete=models.CASCADE)
    content = models.IntegerField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')
    

data4u/forms.py
from django import forms
from data4u.models import Question_4, Answer

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question_4
        fields = ['subject', 'content1', 'content2', 'content3', 'content4']
        # widgets = {
        #     'subject': forms.TextInput(attrs={'class': 'form-control'}),
        #     'content1': forms.Textarea(attrs={'class': 'form-control', 'rows': 2}),
        #     'content2': forms.Textarea(attrs={'class': 'form-control', 'rows': 2}),
        #     'content3': forms.Textarea(attrs={'class': 'form-control', 'rows': 2}),
        #     'content4': forms.Textarea(attrs={'class': 'form-control', 'rows': 2}),
        # }
        labels = {
            'subject': '제목',
            'content1': '첫 번째 선택지',
            'content2': '두 번째 선택지',
            'content3': '세 번째 선택지',
            'content4': '네 번째 선택지',
        }  

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels ={
            'content' : '답변 내용',
        }

data4u/views/answer_views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone
from django.http import HttpResponseNotAllowed
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from ..models import Question_4, Answer
from ..forms import QuestionForm, AnswerForm
from accounts.models import Profile
# Create your views here.abs()



@login_required(login_url='accounts:login')
def answer_create(request, question_id):
    try:
        profile = get_object_or_404(Profile, user=request.user)
    except:
        messages.error(request, '프로필을 먼저 등록해주세요.')
        return redirect('accounts:profile', request.user.id)
    
    question = get_object_or_404(Question_4, pk=question_id)
    if request.user == question.author:
        messages.error(request, '자신의 질문엔 투표할 수 없습니다.')
        return redirect('data4u:detail', question_id=question_id)
    
    if request.method == 'POST':
        if question.answer_set.filter(author=request.user.id) :
            messages.error(request, '한번만 답변할 수 있습니다.')
            return redirect('data4u:detail', question_id=question_id)
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            # 포인트 얻음
            profile.point += 100
            profile.save()
            return redirect('{}#answer_{}'.format(resolve_url('data4u:detail', question_id=answer.question.id), answer.id))
    else:
        return HttpResponseNotAllowed('Only POST is possible.')


@login_required(login_url='accounts:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('data4u:detail', question_id=answer.question.id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()  # 수정일시 저장
            answer.save()
            return redirect('{}#answer_{}'.format(resolve_url('data4u:detail', question_id=answer.question.id), answer.id))
    else:
        form = AnswerForm(instance=answer)
        question = get_object_or_404(Question_4, pk=answer.question.id)
    context = {'answer' : answer, 'form' : form, 'question' : question}
    return render(request, 'data4u/answer_form.html', context)


@login_required(login_url='accounts:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('data4u:detail', question_id=answer.question.id)
    answer.delete()
    return redirect('data4u:detail', question_id=answer.question.id)


@login_required(login_url='accounts:login')
def answer_vote(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인의 답변엔 투표할 수 없습니다')
    else:
        answer.voter.add(request.user)
    return redirect('{}#answer_{}'.format(resolve_url('data4u:detail', question_id=answer.question.id), answer.id))

data4u/views/base_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.http import HttpResponseNotAllowed
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from ..models import Question_4, Answer
from ..forms import QuestionForm, AnswerForm

# Create your views here.


def index(request):
    page = request.GET.get('page', '1') 	# 페이지
    kw = request.GET.get('kw', '')			# 검색어
    question_list = Question_4.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content1__icontains=kw) |  # 내용1 검색
            Q(content2__icontains=kw) |  # 내용2 검색
            Q(content3__icontains=kw) |  # 내용3 검색
            Q(content4__icontains=kw) |  # 내용4 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw)   # 질문 글쓴이 검색
        ).distinct()
    
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)
    context = {'question_list' : page_obj, 'page':page, 'kw':kw}
    return render(request, 'data4u/question_list.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question_4, pk=question_id)
    context = {'question':question}
    # 각 문항별 횟수
    count_list = []
    for i in range(1, 5):
        count_list.append(question.answer_set.filter(content=i).count())
    context = {'question':question, 'count_list':count_list}
    return render(request, 'data4u/question_detail.html', context)

data4u/views/question_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.http import HttpResponseNotAllowed
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from ..models import Question_4, Answer
from ..forms import QuestionForm, AnswerForm
from accounts.models import Profile
# Create your views here.


@login_required(login_url='accounts:login')
def question_create(request):
    try:
        profile = get_object_or_404(Profile, user=request.user)
        if profile.point >= 1000:
            pass
        else:
            messages.error(request, '포인트를 충전해주세요.')
            return redirect('accounts:profile', request.user.id)
    except:
        messages.error(request, '프로필을 먼저 등록해주세요.')
        return redirect('accounts:profile', request.user.id)
    
    if request.method == 'POST' :
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            
            # 포인트 차감 -1000
            profile.point -= 1000
            profile.save()
            
            return redirect('data4u:index')
    else:
    	form = QuestionForm(initial={'subject': '제목을 입력하세요.', 'content1':'1번 선택지', 'content2':'2번 선택지', 'content3':'3번 선택지', 'content4':'4번 선택지'})
    context = {'form':form}
    return render(request, 'data4u/question_form.html', context)


@login_required(login_url='accounts:login')
def question_modify(request, question_id):
    question = get_object_or_404(Question_4, pk=question_id)
    if request.user != question.author :
        messages.error(request, '수정권한이 없습니다.')
        return redirect('data4u:detail', question_id=question.id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()  # 수정일시 저장
            question.save()
            return redirect('data4u:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form' : form}
    return render(request, 'data4u/question_form.html', context)


@login_required(login_url='accounts:login')
def question_delete(request, question_id):
    question = get_object_or_404(Question_4, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('data4u:detail', question_id=question.id)
    question.delete()
    return redirect('data4u:index')


@login_required(login_url='accounts:login')
def question_vote(request, question_id):
    question = get_object_or_404(Question_4, pk=question_id)
    if request.user == question.author:
        messages.error(request, '본인 질문에는 투표할 수 없습니다.')
    else:
        question.voter.add(request.user)
    return redirect('data4u:detail', question_id=question.id)

templates/data4u/answer_form.html
{% extends 'base.html' %}
{% block content %}
<!-- 답변 수정-->
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">답변 내용</label>
        	<div class="my-3">
    			<p><label><input {% if not user.is_authenticated %}disabled{% endif %} type="checkbox" name="content" value= 1> 1번: {{ question.content1|default_if_none:'' }} </label></p>
    			<p><label><input {% if not user.is_authenticated %}disabled{% endif %} type="checkbox" name="content" value= 2> 2번: {{ question.content2|default_if_none:'' }} </label></p>
    			<p><label><input {% if not user.is_authenticated %}disabled{% endif %} type="checkbox" name="content" value= 3> 3번: {{ question.content3|default_if_none:'' }} </label></p>
    			<p><label><input {% if not user.is_authenticated %}disabled{% endif %} type="checkbox" name="content" value= 4> 4번: {{ question.content4|default_if_none:'' }} </label></p>
        	</div>
        </div>
        <button type="submit" class="btn" style="color: white; background-color: #0099FF;">저장하기</button>
    </form>
</div>
{% endblock %}

templates/data4u/question_detail.html
{% extends 'base.html' %}
{% load data4u_filter %}
{% block content %}
<div class="container my-3">
    <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card">
        <div class="card-body">
            <a href="javascript:void(0)" data-uri="{% url 'data4u:question_vote' question.id  %}"
               class="recommend btn btn-sm btn-outline-secondary"> 추천
                <span class="badge rounded-pill" style="color: white; background-color: #0099FF;">{{question.voter.count}}</span>
            </a>
            <div class="d-flex justify-content-start">
                <div class="my-3">
                    {% if request.user == question.author %}
                    <a href="{% url 'data4u:question_modify' question.id  %}" 
                       class="btn btn-sm btn-outline-secondary">질문 수정</a>
                    <a href="javascript:void(0)" data-uri="{% url 'data4u:question_delete' question.id  %}" 
                       class="delete btn btn-sm btn-outline-secondary">질문 삭제</a>
                    {% endif %}
                </div>
            </div>
            
            <div class="d-flex justify-content-start">
            	{% if question.modify_date %}
            	<div class="badge text-dark p-2 text-start mx-3">
            	    <div class="mb-2">modified at</div>
            	    <div>{{ question.modify_date }}</div>
            	</div>
            	{% endif %}
                <div class="badge text-dark p-2 text-start">
                    <div class="mb-2">{{ question.author.username }}</div>
                    <div>{{ question.create_date }}</div>
                </div>
            </div>
        </div>
    </div>
    <p>
        
    </p>
    <!-- 답변 등록 -->
    <form action="{% url 'data4u:answer_create' question.id %}" method="post">
    	{% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="my-3">
    		<p><label><input {% if not user.is_authenticated %}disabled{% endif %} type="checkbox" name="content" value= 1> 1번: {{ question.content1 }} </label></p>
    		<p><label><input {% if not user.is_authenticated %}disabled{% endif %} type="checkbox" name="content" value= 2> 2번: {{ question.content2 }} </label></p>
    		<p><label><input {% if not user.is_authenticated %}disabled{% endif %} type="checkbox" name="content" value= 3> 3번: {{ question.content3 }} </label></p>
    		<p><label><input {% if not user.is_authenticated %}disabled{% endif %} type="checkbox" name="content" value= 4> 4번: {{ question.content4 }} </label></p>
        </div>
		<p><button class="btn mt-4" style="color: white; background-color: #0099FF;" type="submit">답변 등록</button>
	</form>
    <p>
        
    </p>
    <!-- 답변 통계 -->
    <h5 class="border-bottom my-3 py-2 mt-5">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for value in count_list %}
    <a id="answer_{{ answer.id }}"></a>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">{{ forloop.counter }}번은 {{ value }}명이 선택했습니다.</div>
        </div>
    </div>
    {% endfor %}
    <!-- {% for answer in question.answer_set.all %}
    <a id="answer_{{ answer.id }}"></a>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">{{ answer.content|mark }}</div>
            <div class="d-flex justify-content-end">
            	{% if answer.modify_date %}
            	<div class="badge text-dark p-2 text-start mx-3">
            	    <div class="mb-2">modified at</div>
            	    <div>{{ answer.modify_date }}</div>
            	</div>
            	{% endif %}
                <div class="badge text-dark p-2 text-start">
                    <div class="mb-2">{{ answer.author.username }}</div>
                    <div>{{ answer.create_date }}</div>
                </div>
            </div>
            <a href="javascript:void(0)" data-uri="{% url 'data4u:answer_vote' answer.id  %}"
               class="recommend btn btn-sm btn-outline-secondary"> 추천
                <span class="badge rounded-pill bg-success">{{answer.voter.count}}</span>
            </a>
            {% if request.user == answer.author %}
            <a href="{% url 'data4u:answer_modify' answer.id  %}" class="btn btn-sm btn-outline-secondary">답변 수정</a>
            <a href="#" data-uri="{% url 'data4u:answer_delete' answer.id  %}" class="delete btn btn-sm btn-outline-secondary">답변 삭제</a>
            {% endif %}
        </div>
    </div>
    {% endfor %} -->
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
    
const recommend_elements = document.getElementsByClassName("recommend");
Array.from(recommend_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

templates/data4u/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문 등록</h5>
    <form method="post">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">사지 선다</label>
            <textarea class="form-control mp-2" name="content1"
                      id="content" rows="6">{{ form.content1.value|default_if_none:'' }}</textarea>
            <textarea class="form-control mp-2" name="content2"
                      id="content" rows="6">{{ form.content2.value|default_if_none:'' }}</textarea>
            <textarea class="form-control mp-2" name="content3"
                      id="content" rows="6">{{ form.content3.value|default_if_none:'' }}</textarea>
            <textarea class="form-control mp-2" name="content4"
                      id="content" rows="6">{{ form.content4.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn" style="color: white; background-color: #0099FF;">저장하기</button>
    </form>
</div>
{% endblock %}

templates/data4u/question_list.html
{% extends 'base.html' %}
{% load data4u_filter %}
{% block content %}
<div class="container my-3">
    <div class="row mt-5 justify-content-center">
        <div style="margin-bottom:5%;">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">검색</button>
                </div>
            </div>
        </div>
    </div>
	<div class="row row-cols-1 row-cols-md-2 g-4">
      {% if question_list %} 
      {% for question in question_list %}
      <div class="col mt-6">
          <div class="card" style="height:280px;">
              <div class="card-body ">
                  <h3 class="card-title" style="font-weight:bold; margin-bottom: 17%;">{{ question.subject }}</h3>
                  <div class="card-text mt-5">
                      <p>질문자: {{ question.author.username }}
                          <br> 
                      게시날: {{ question.create_date }}
                      </p>
                  </div>
                  <a href="{% url 'data4u:detail' question.id %}">
                      <button type="button" class="btn" style="color: white; background-color: #0099FF;">
                          {% if question.answer_set.count > 0 %}
                          <span class="text-white small mx-2">{{ question.answer_set.count }} 명 참가</span>
                          {% else %}
                          Answer
                          {% endif %}
                      </button>
                  </a>
              </div>
          </div>  
	  </div>
      {% endfor %}
      {% else %}
	  <div class="card">
	    <div class="card-body">
	      <h5 class="card-title">질문이 없습니다.</h5>
	    </div>
	  </div>  
      {% endif %}
	</div>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.previous_page_number }}"
               href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-2 and page_number <= question_list.number|add:2 %}
        {% if page_number == question_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" data-page="{{ page_number }}"
               href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_number }}"
               href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% endif %}
    	{% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.next_page_number }}"
               href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
</div>
<form id="searchForm" method="get" action="{% url 'index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}

templates/data4u/question_list_1.html
{% extends 'base.html' %}
{% load data4u_filter %}
{% block content %}
<div class="container my-3">
    <div class="row my-3 justify-content-center">
        <!-- <div class="col-6">
            <a href="{% url 'data4u:question_create' %}" class="btn" style="color: white; background-color: #0099FF;">질문 등록하기</a>
        </div> -->
        <div>
            <div class="input-group w-50">
                <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr class="text-center table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>질문자</th>
            <th>작성 일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr class="text-center">
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ question_list.paginator.count | sub:question_list.start_index | sub:forloop.counter0|add:1 }}
            </td>
            <td class="text-start">
                <a href="{% url 'data4u:detail' question.id %}" style='text-decoration:none; font-weight:bold;'>{{ question.subject }}</a>
            	{% if question.answer_set.count > 0 %}
                <span class="text-danger small mx-2">{{ question.answer_set.count }}</span>
                {% endif %}
            </td>
            <td>{{ question.author.username }}</td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.previous_page_number }}"
               href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-2 and page_number <= question_list.number|add:2 %}
        {% if page_number == question_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" data-page="{{ page_number }}"
               href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_number }}"
               href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% endif %}
    	{% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.next_page_number }}"
               href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
</div>
<form id="searchForm" method="get" action="{% url 'index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}