accounts/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from accounts.views import account_views, profile_views, kakaopay_views  

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', account_views.signup, name='signup'),	
    path('profile/<int:pk>', profile_views.profile, name='profile'),
    path('profile/<int:pk>/register', profile_views.profile_register, name='profile_register'),
    path('profile/<int:pk>/modify', profile_views.profile_modify, name='profile_modify'),
    path('profile/<int:pk>/point', profile_views.point_charge, name='point_charge'),
    path('kakaoPay/', kakaopay_views.kakaoPay, name='kakaoPay'),
    path('paySuccess/', kakaopay_views.paySuccess, name='paySuccess'),
    path('payFail/', kakaopay_views.payFail, name='payFail'),
    path('payCancel/', kakaopay_views.payCancel, name='payCancel'),
]

if settings.DEBUG: 
    urlpatterns += static(
        settings.MEDIA_URL, 
        document_root = settings.MEDIA_ROOT
    )

data4u/urls.py
from django.urls import path, include
from .views import base_views, question_views, answer_views

app_name = 'data4u'

urlpatterns = [
    # base views
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),
    
    # question views
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),
    
    # answer views
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),
]

data4u_mvp/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from data4u.views import base_views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('data4u/', include('data4u.urls')),
    path('accounts/', include('accounts.urls')),
    path('', base_views.index, name='index'),
]

# MEDIA_URL로 들어오는 요청에 대해 MEDIA_ROOT 경로를 탐색한다.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

data4u/views/base_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.http import HttpResponseNotAllowed
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from ..models import Question_4, Answer
from ..forms import QuestionForm, AnswerForm

# Create your views here.


def index(request):
    page = request.GET.get('page', '1') 	# 페이지
    kw = request.GET.get('kw', '')			# 검색어
    question_list = Question_4.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content1__icontains=kw) |  # 내용1 검색
            Q(content2__icontains=kw) |  # 내용2 검색
            Q(content3__icontains=kw) |  # 내용3 검색
            Q(content4__icontains=kw) |  # 내용4 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw)   # 질문 글쓴이 검색
        ).distinct()
    
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)
    context = {'question_list' : page_obj, 'page':page, 'kw':kw}
    return render(request, 'data4u/question_list.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question_4, pk=question_id)
    context = {'question':question}
    # 각 문항별 횟수
    count_list = []
    for i in range(1, 5):
        count_list.append(question.answer_set.filter(content=i).count())
    context = {'question':question, 'count_list':count_list}
    return render(request, 'data4u/question_detail.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- data4u CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    
    <!-- 폰트적용 -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jua&display=swap" rel="stylesheet">
    <style>
        *{ font-family: 'Jua', sans-serif; }
    </style>
    <title>Data4U!</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
{% load static %}
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
      	<!-- <a class="navbar-brand" href="{% url 'data4u:index' %}">
      	  <img src='{% static "img/data4u.jpg" %}' width="30%" alt="logo">
      	</a> -->
        <a class="navbar-brand justify-content-center" href="{% url 'data4u:index' %}"><img src='{% static "img/data4u.jpg" %}' width="13%" alt="logo"> DATA4U</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'data4u:index' %}">홈</a>
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'accounts:profile' user.id %}">프로필</a>
                    <a class="nav-link" href="{% url 'accounts:logout' %}">{{ user.username }} (로그아웃)</a>
    				{% else %}
                    <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>